### ISSUE TITLE
inc and add should return counter value

### ISSUE THREAD

**Issue by ChrisJefferson** [kosta/atomic-counter#1]
Hi,

At the moment, I can't in a threadsafe way increment the counter, and get the newly incremented value.

**Comment by kosta** [comment]
Wow, I'm a bit flabbergasted! This is a major oversight. Thanks for pointing this out!

Do you want to send a PR? Otherwise I hope I can fix it this week.

**Comment by kosta** [comment]
Can you take a look at #2 ? It's a simple change but I'd like your feedback before I merge & do a cargo release.

**Comment by ChrisJefferson** [comment]
That looks great, thanks :)

**Comment by ChrisJefferson** [comment]
On a totally crazy suggestion, if after doing this the package feels "complete" (it does to me, at doing thing), you could consider going 1.0.0 version, to make it clear it's ready for use (I'm always worried about 0.1.x packages, as I assume they are pre-useful). Of course that makes it harder to make significant ABI changes.

**Comment by kosta** [comment]
Thank you! I think so, too.

We can always go 2.0.0 if we need to revamp the API :)

**Comment by kosta** [comment]
[They grow up so fast!](https://crates.io/crates/atomic-counter)
