### ISSUE TITLE
Recommendation for serializing a RelaxedCounter?

### ISSUE THREAD

**Issue by sowbug** [kosta/atomic-counter#6]
I'd like to be able to include a `RelaxedCounter` in a struct that is `#[derive(Serialize, Deserialize)]`, but I can't because `RelaxedCounter` doesn't support Serde. My use case is a factory struct that mints things with unique IDs. All these things belong to a project that gets saved to and loaded from disk. Since the factory can continue minting things after being restored from disk, it needs to remember its last-minted UID so that it doesn't start reissuing from already-used low numbers.

Serde knows how to serialize `AtomicUsize`. But not `RelaxedCounter`. So I've written this code to run after every deserialization:

```
    fn set_next_uid(&self, next_uid_value: usize) {
        self.next_uid.reset();
        self.next_uid
            .add(next_uid_value.max(1));
    }
```

and then I serialize the highest minted UID elsewhere as a usize, which Serde of course has no problem with. This works, but it feels clunky because `RelaxedCounter` has no direct set() method (no doubt intentionally, because that makes it a little too easy to violate the constraint of monotonicity).

Given my specific use case, some of the warning bells going off (`set_next_uid()` is racy, etc.) don't apply, or are acceptable risks. So the very idea of serialization might be fine with me but unacceptable for the general `atomic-counter` crate. I'm OK with that, but before I give up, I'd like to ask whether there's a simple way to serialize `RelaxedCounter` that I haven't thought of. I'm OK dropping down to `AtomicUsize` if that's the better approach.

Thanks!

**Comment by kosta** [comment]
I think the best way is to add a „Serde“ feature to this crate in which the (de)serialization is implemented. 

Until then, can you try using [serialize_with](https://serde.rs/field-attrs.html#serialize_with) to serialize the Counter?

**Comment by kosta** [comment]
(Reopened as close was just a misclick)

**Comment by sowbug** [comment]
I see no reason why I could not use `serialize_with`, except that it hadn't occurred to me until you mentioned it. I'll give that a whirl and reopen if there are any roadblocks. Thanks!
